### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by sunjieemm** [metaphysicser/PS-Mixer#1]
https://github.com/metaphysicser/PS-Mixer/blob/3e4fc7fc75b73c90f34e699bf5faac22d18d7022/new_models.py#L124
Hi, 
I found a bug "'PS_Mixer' object has no attribute 'vlayer_norm'"

**Comment by pinglu-zhang** [comment]
Thank you for finding the bug.  I have completed the missing code in 77-79 line of new_model.py
