### ISSUE TITLE
No module named 'utils.time_track'

### ISSUE THREAD

**Issue by JackAILab** [metaphysicser/PS-Mixer#3]
I run the main.py, but receive the loss of one python file.
Can you provide this file for me?

Thank you a lot！

<img width="1920" alt="20230410121040" src="https://user-images.githubusercontent.com/112920087/230824267-108a48f3-310c-452f-b23c-584cc55f90a4.png">

**Comment by pinglu-zhang** [comment]
I'm sorry for forgetting to upload time_track.py due to my negligence. You could pull the new code.
